import { Tabs } from 'components';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import classes from 'styles/Home.module.css';
import { HOME_TABS } from 'variables';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={`${classes.main} container`}>
        <h1>Qidirish</h1>
        <Tabs tabs={HOME_TABS} />
      </main>

      <footer className={classes.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={classes.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
